# Generated by Django 4.2.2 on 2024-02-18 15:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'staff'), (3, 'Student'), (4, 'Instructor'), (5, 'Examiner'), (6, 'Principal')], default=1, max_length=10)),
                ('profile_img', models.ImageField(null=True, upload_to='user_img/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_code', models.CharField(max_length=50, unique=True)),
                ('sem_no', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255, unique=True)),
                ('c_code', models.CharField(max_length=255, unique=True)),
                ('c_type', models.CharField(max_length=10)),
                ('c_duration', models.CharField(max_length=4)),
                ('c_qualification', models.CharField(max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_code', models.CharField(max_length=255, unique=True)),
                ('mode_name', models.CharField(max_length=255)),
                ('duration_hours', models.PositiveIntegerField()),
                ('academic_weeks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionYr',
            fields=[
                ('yr_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('tr_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_code', models.CharField(max_length=255, unique=True)),
                ('sub_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.course')),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('adrz', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('nic', models.CharField(max_length=20, unique=True)),
                ('st_idNo', models.CharField(max_length=100, null=True, unique=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('mobileNo', models.CharField(max_length=10)),
                ('resiNo', models.CharField(max_length=10, null=True)),
                ('civil_status', models.CharField(max_length=10, null=True)),
                ('edu_qualification', models.CharField(max_length=10, null=True)),
                ('prof_qualification', models.CharField(max_length=10, null=True)),
                ('other_qualification', models.CharField(max_length=255, null=True)),
                ('guardian_name', models.CharField(max_length=100, null=True)),
                ('guardian_contNo', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('b_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.batch')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.course')),
                ('tr_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.trade')),
                ('yr_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.sessionyr')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sf_id', models.AutoField(primary_key=True, serialize=False)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('adrz', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('nic', models.CharField(max_length=20)),
                ('sf_idNo', models.CharField(max_length=50, null=True, unique=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('civil_status', models.CharField(max_length=10, null=True)),
                ('mobileNo', models.CharField(max_length=11)),
                ('resiNo', models.CharField(max_length=11, null=True)),
                ('edu_qualification', models.CharField(max_length=10, null=True)),
                ('prof_qualification', models.CharField(max_length=255, null=True)),
                ('other_qualification', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('completed_hours', models.PositiveIntegerField()),
                ('completed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.course')),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.module')),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.batch')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.course')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSf',
            fields=[
                ('nfysf_id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_sf', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationS',
            fields=[
                ('nfy_id', models.AutoField(primary_key=True, serialize=False)),
                ('notify', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.subject'),
        ),
        migrations.CreateModel(
            name='LeaveReportSf',
            fields=[
                ('lrs_id', models.AutoField(primary_key=True, serialize=False)),
                ('lrs_date', models.DateField()),
                ('lrs_msg', models.TextField()),
                ('lrs_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportS',
            fields=[
                ('lr_id', models.AutoField(primary_key=True, serialize=False)),
                ('lr_date', models.DateField()),
                ('lr_msg', models.TextField()),
                ('lr_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSf',
            fields=[
                ('fbs_id', models.AutoField(primary_key=True, serialize=False)),
                ('fbs', models.CharField(max_length=255)),
                ('fbs_rpy', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.staff')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackS',
            fields=[
                ('fb_id', models.AutoField(primary_key=True, serialize=False)),
                ('fb', models.CharField(max_length=255)),
                ('fb_rpy', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.trade'),
        ),
        migrations.AddField(
            model_name='batch',
            name='c_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mistech.course'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False)),
                ('at_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.batch')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.course')),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.subject')),
                ('yr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.sessionyr')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
