# Generated by Django 4.2.2 on 2024-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sf_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='sf_id',
            field=models.ManyToManyField(to='mistech.staff'),
        ),
    ]
