# Generated by Django 4.2.2 on 2024-02-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0002_remove_subject_sf_id_subject_sf_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceE',
            fields=[
                ('ae_id', models.AutoField(primary_key=True, serialize=False)),
                ('ae_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('ex_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.batch')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.course')),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mistech.subject')),
                ('yr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.sessionyr')),
            ],
        ),
    ]
