# Generated by Django 4.2.2 on 2024-03-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0003_attendancee'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='c_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mistech.course'),
        ),
    ]
