# Generated by Django 4.2.2 on 2024-03-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0004_module_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='mode_name',
            new_name='mod_name',
        ),
    ]
