# Generated by Django 4.2.2 on 2024-03-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0005_rename_mode_name_module_mod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lplan',
            fields=[
                ('lp_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_activity', models.CharField(max_length=255)),
                ('methodology', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=255)),
                ('time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tk_name', models.CharField(max_length=255, unique=True)),
                ('tk_date', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.module')),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AddField(
            model_name='lplan',
            name='tk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.task'),
        ),
    ]
