# Generated by Django 4.2.2 on 2024-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0006_lplan_task_delete_plan_lplan_tk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lplan',
            name='time',
        ),
        migrations.AddField(
            model_name='lplan',
            name='lp_time',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tk_wk',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('not_complete', 'Not Complete')], default='not_complete', max_length=15),
        ),
    ]
