# Generated by Django 4.2.2 on 2024-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0007_remove_lplan_time_lplan_lp_time_task_tk_wk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'Completed'), ('not_complete', 'Not Completed')], default='not_complete', max_length=15),
        ),
    ]
