# Generated by Django 4.2.2 on 2024-03-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0008_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_exam_marks', models.FloatField(default=0)),
                ('sub_asgn_marks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistech.subject')),
            ],
        ),
    ]
