# Generated by Django 4.2.2 on 2024-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0009_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobileNo',
            field=models.CharField(max_length=12),
        ),
    ]
