# Generated by Django 4.2.2 on 2024-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0010_alter_staff_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileNo',
            field=models.CharField(max_length=12),
        ),
    ]
