# Generated by Django 4.2.2 on 2024-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0011_alter_student_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
