# Generated by Django 4.2.2 on 2024-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0012_staff_fcm_token_student_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportsf',
            name='medical_img',
            field=models.ImageField(null=True, upload_to='user_img/'),
        ),
    ]
