# Generated by Django 4.2.2 on 2024-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0013_leavereportsf_medical_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsf',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavereportsf',
            name='medical_img',
            field=models.ImageField(null=True, upload_to='medical_img/'),
        ),
    ]
