# Generated by Django 4.2.2 on 2024-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0014_notificationsf_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportsf',
            name='reason_lv',
            field=models.TextField(default=True),
        ),
    ]
