# Generated by Django 4.2.2 on 2024-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistech', '0015_leavereportsf_reason_lv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportsf',
            name='reason_lv',
            field=models.TextField(null=True),
        ),
    ]
